name: Create Pull Request

on:
  push:
    branches:
      - 'feature**'
      - 'fix**'

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/my-feature
          title: "Feature: Implement my-feature"
          body: "This pull request implements the changes for my-feature."
          base: develop
